@startuml Create Order en Guest
actor "GUEST" as G
participant "OrderController" as OC
participant "IOrderService" as IOS
participant "OrderServiceImpl" as OSI
participant "ProductRepository" as PR
participant "OrderRepository" as OR

G -> OC: POST /api/orders (liste de produits)
OC -> IOS: createOrderAsGuest(dto)
IOS -> OSI: createOrderAsGuest(dto)
OSI -> PR: checkStock(productIds)
PR --> OSI: product data
OSI -> OR: save(order)
OR --> OSI: order saved
OSI --> IOS: order
IOS --> OC: order
OC --> G: 200 OK + JSON
@enduml