@startuml
left to right direction

actor Utilisateur as "Utilisateur"
actor Administrateur as "Administrateur"

rectangle Réservations{
  usecase "Réserver une séance" as (Réserver)
  usecase "Consulter les réservations" as (Consulter)
  usecase "Gérer les réservations" as (Gérer)
  usecase "Valider les réservations" as (Valider)

  Utilisateur -- (Réserver)
  Utilisateur -- (Consulter)
  Administrateur -- (Gérer)
  Administrateur -- (Valider)

  (Réserver) ..> (Valider) : <<include>>
  (Gérer) ..> (Valider) : <<include>>
}

@enduml